AWSTemplateFormatVersion: 2010-09-09
Description: Create Infrastructure for Contentful Boilerplate 1.
Parameters:
  BucketName:
    Type: String
  Customer:
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      Tags:
        -
          Key: "CUSTOMER"
          Value: !Ref Customer
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Sub arn:aws:s3:::${S3Bucket}/*

  Cloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      Tags:
        -
          Key: "CUSTOMER"
          Value: !Ref Customer
      DistributionConfig:
        Origins:
        - Id: S3Origin
          DomainName: !Sub ${BucketName}.s3-website.${AWS::Region}.amazonaws.com
          CustomOriginConfig:
            HTTPPort: 80
            HTTPSPort: 443
            OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_All

Outputs:
  CloudfrontDistributionID:
    Value: !Ref Cloudfront